name: Prenotazione Automatica Piscina

on:
  schedule:
    # Formato Cron: Minuti, Ore, GiornoMese, Mese, GiornoSettimana
    # I giorni della settimana vanno da 0 (Domenica) a 6 (Sabato).
    # 2 = Martedì, 3 = Mercoledì.
    # Ore: 06 (UTC) -> Corrisponde alle 07:00 in Italia (solare) o 08:00 (legale).
    - cron: '0 6 * * 2,3'
  
  # Questo parametro ti permette di avviare lo script a mano cliccando un pulsante su GitHub
  workflow_dispatch:

jobs:
  esegui-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v3

      - name: Prepara Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa la libreria requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Lancia lo script di prenotazione
        run: python prenota.py
        env:
          # Permette di passare l'ID in modo sicuro tramite i Secret di GitHub (opzionale)
          ID_UTENTE: ${{ secrets.ID_UTENTE }}
