name: Prenotazione Automatica Piscina

on:
  schedule:
    # Esegue il bot alle 07:00 ora italiana (06:00 UTC) ogni Martedì (2) e Mercoledì (3).
    # Sostituisci il "6" con l'orario in cui aprono le iscrizioni (es. se aprono a mezzanotte, metti "23" del giorno prima).
    - cron: '0 6 * * 2,3'
  
  workflow_dispatch:

jobs:
  esegui-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Prepara Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa librerie
        run: pip install requests

      - name: Lancia lo script di prenotazione
        run: python prenota.py
